= Setup
include::_attributes.adoc[]
:git_folder: tssc-demo

[#prerequisite]
== Prerequisite Tools

[IMPORTANT]
.Visual Studio Code Remote Development (Containers)
====
To limit the amount of incompatibility in setting up the demo and tutorial, all the commands that are listed are expected to be run in an appropriately setup container.  Specifically, this demo supports the link:https://code.visualstudio.com/docs/remote/containers[VS Code Remote Development (Containers)] as can be seen in the `.devcontainer` directory.  

All commands that are listed for the demo and tutorial are assumed to be run from within the terminal (and thus "devcontainer") of VSCode.  The container has been setup to have all the necessary command and tools necessary to run and compile the tutorial/demo.

This tutorial/demo was developed using Visual Studio Code Remote Development on a MacBook Pro using Docker for Desktop (Mac)
====

You must have cluster-admin access to an OpenShift 4.6 cluster to be able to run the walkthrough demos

[#demo-setup]
== Demo Setup

. Clone the repo onto your local machine
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
git clone {git_repo} --recurse-submodules {git_folder}
----
+
. Change into that directory and start vscode
+
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cd {git_folder}
code .
----
+
. When prompted to open the folder in a container, accept.
+
. Use kbd:[cmd + j] to open the terminal
+
. Log into an OpenShift 4.6 cluster using the `oc login` command
. Once logged in, run the following command in the terminal:
+
[.console-input]
[source,bash]
----
$DEMO_HOME/scripts/create_demo.sh -i
----
