---
- name: Create Rekor 
  include_tasks: provision_rekor.yaml

- name: Create Ploigos Platform
  include_tasks: provision_ploigos_platform_helm.yaml
  when:
    - ploigos_platform_full_install is defined
    - ploigos_platform_full_install | bool 

- name: Install Ploigos Platform Support
  include_role: 
    name: ploigos_support
  vars:
    ploigos_cleanup: false
  when:
    - (ploigos_platform_full_install is not defined) or not (ploigos_platform_full_install | bool) 

- name: Create Ploigos Pipeline
  include_tasks: provision_ploigos_pipeline.yaml
  when:
    - ploigos_platform_full_install is defined
    - ploigos_platform_full_install

