---
- name: Generate Helm values file
  template:
    src: templates/ploigos/ploigos-pipeline-helm-values.yaml.j2
    dest: /tmp/values.yml

# FIXME: Also check for successful chart install
- name: Check if helm chart exists
  shell: |
    if [[ -n "$(helm list -n {{ ploigos_namespace }} --deployed | grep ploigos)" ]]; then echo "true"; else echo "false"; fi
  register: result
  failed_when: result.rc != 0

- name: Set chart_installed
  set_fact:
    chart_installed: "{{ result.stdout_lines[0] }}"
 
- name: Debug Chart
  debug:
    msg: "Chart installed is: {{ chart_installed }}"

- name: Run the ploigos helm chart
  shell: |
    cd $DEMO_HOME/helm/charts/ploigos
    helm upgrade --install ploigos . --namespace {{ ploigos_namespace }} --create-namespace -f /tmp/values.yml
  when: ( not chart_installed )

# FIXME: Hack related to issue in Ploigos operator
# The rhsso-operator needs permission to be able to do things like creating a route
# which it doesn't appear to be able to do by default
- name: "HACK: give rhsso-operator elevated privileges"
  shell: |
    oc adm policy add-cluster-role-to-user cluster-admin -n {{ ploigos_namespace }} -z rhsso-operator 
  register: adm_result
  until: adm_result.rc == 0
  retries: 10
  delay: 2

- name: Wait for Platform to finish
  k8s_info:
    kind: TsscPlatform
    name: tsscplatform-jenkins
    namespace: '{{ ploigos_namespace }}'
    api_version: redhatgov.io/v1alpha1
  register: r_k8s_info
  until: (r_k8s_info.resources[0].status.conditions[0].reason | default(0) == "Successful")
    and (r_k8s_info.resources[0].status.conditions[0].status | default(0) == "True")
  retries: 10
  delay: 2
  when: ( wait_for_ploigos_crs | bool )

# - name: Debug platform status
#   debug: 
#     msg: "Reason: {{ r_k8s_info.resources[0].status.conditions[0].reason }}.  Status: {{ r_k8s_info.resources[0].status.conditions[0].status }}"