---
- name: vars
  set_fact:
      operators_project: 'openshift-operators'

- name: Uninstall Streams
  block:
    - name: Get Sub
      k8s_info:
        kind: Subscription
        api_version: operators.coreos.com/v1alpha1
        namespace: '{{ operators_project }}'
        name: amq-streams
      register: sub_info
    # - name: Print Sub
    #   debug:
    #     msg: "current sub is: {{ sub_info }}"
    # - name: Print CSV
    #   debug:
    #     msg: "current csv is: {{ sub_info | json_query('resources[*].status.currentCSV') }}"
    # - name: Set CSV
    #   set_fact:
    #     streams_csv: "{{ sub_info | json_query('resources[*].status.currentCSV') }}"
    - name: Print CSV Fact
      debug:
        msg: "current csv is: {{ item }}"
      loop: "{{ sub_info | json_query('resources[*].status.currentCSV') }}"
    
    - name: Delete Subscription
      k8s:
        state: absent
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: amq-streams
        namespace: '{{ operators_project }}'

    - name: Delete ClusterServiceVersion
      k8s:
        state: absent
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: '{{ item }}'
        namespace: '{{ operators_project }}'
      loop: "{{ sub_info | json_query('resources[*].status.currentCSV') }}"

    - name: Collect CustomResourceDefintions
      k8s_info:
        api_version: apiextensions.k8s.io/v1beta1
        kind: CustomResourceDefinition
        label_selectors:
        - app=strimzi
      register: crds_list
    - name: Delete CustomResourceDefinitions
      k8s:
        state: absent
        api_version: apiextensions.k8s.io/v1beta1
        kind: CustomResourceDefinition
        name: '{{ item.metadata.name }}'
      loop: '{{ crds_list.resources }}'
  when: remove_operators|bool

- name: Delete demo projects
  k8s:
    state: absent
    kind: Namespace
    name: '{{ item }}'
  loop:
    - "{{ coolstore_project }}"
    - "{{ legacy_app_project }}"
    - "{{ dbz_project }}"
    - "{{ sandbox_project }}"
    - "{{ dev_project }}"
    - "{{ kafka_project }}"
    - "{{ db_project }}"

# Leave this as the last task in the playbook.
- name: Remove workload tasks complete
  debug:
    msg: "Remove Workload Tasks completed successfully."
  when: not silent|bool