- name: Remove Operators
  include_tasks: remove_operators.yaml
  when: (remove_operators == "true" ) 

# - name: Delete demo projects
#   k8s:
#     state: absent
#     kind: Namespace
#     name: '{{ item }}'
#   loop:
#     - "{{ coolstore_project }}"
#     - "{{ legacy_app_project }}"
#     - "{{ dbz_project }}"
#     - "{{ sandbox_project }}"
#     - "{{ dev_project }}"
#     - "{{ kafka_project }}"
#     - "{{ db_project }}"

# # Leave this as the last task in the playbook.
# - name: Remove workload tasks complete
#   debug:
#     msg: "Remove Workload Tasks completed successfully."
#   when: not silent|bool