{{- if .Values.operator.namespaces }}
{{- range $key := .Values.operator.namespaces }}
---
apiVersion: redhatgov.io/v1alpha1
kind: TsscPlatform
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  namespace: {{ $key.name }}
  name: tsscplatform-jenkins
spec:
  tsscPlatform:
    helmRepository: 'https://ploigos.github.io/ploigos-charts'
    pullSecret:
      name: installation-pull-secrets
      namespace: openshift-image-registry
    services:
      continuousIntegration:
        name: jenkins
        managed: true
      sourceControl:
        name: gitea
        managed: true
      artifactRepository:
        name: nexus
        managed: true
      staticCodeAnalysis:
        name: sonarqube
        managed: true
      continuousDeployment:
        name: argocd
        managed: true
      uat:
        name: selenium
        managed: true
      containerRegistry:
        name: nexus
        managed: true
{{- end }}
{{- end }}