{{- if .Values.operator.namespaces }}
{{- range $key := .Values.operator.namespaces }}
---
apiVersion: redhatgov.io/v1alpha1
kind: TsscPlatform
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
  namespace: {{ $key.name }}
  name: tsscplatform-jenkins
spec:
  tsscPlatform:
    # pullSecret:
    #   name: installation-pull-secrets
    #   namespace: openshift-image-registry
    services:
      continuousIntegration:
        name: jenkins
      sourceControl:
        name: gitea
      artifactRepository:
        name: nexus
      staticCodeAnalysis:
        name: sonarqube
      continuousDeployment:
        name: argocd
      uat:
        name: selenium
      containerRegistry:
        name: nexus
{{- end }}
{{- end }}