---
# tasks file for ploigos_support
- block:
  - name: Create namespace for ploigos
    k8s:
      state: present
      api_version: v1
      kind: Namespace
      name: "{{ ploigos_namespace }}"

  # - name: Ploigos install Hack
  #   shell: |
  #     oc adm policy add-cluster-role-to-user -n {{ ploigos_namespace }} -z rhsso-operator cluster-admin
  #   register: result
  #   failed_when: result.rc != 0

  - name: Install CatalogSource
    k8s:
      state: present
      resource_definition: "{{ lookup('template', 'catalog-source.yaml.j2') }}"

  - name: Subscribe to Ploigos Operator
    k8s:
      state: present
      resource_definition: "{{ lookup('template', 'subscription.yaml.j2') }}"

  - name: Register Ploigos CSV
    k8s_info:
      api_version: operators.coreos.com/v1alpha1
      kind: Subscription
      namespace: "{{ ploigos_namespace }}"
    register: r_ploigos_sub
    until: 
      - r_ploigos_sub is defined
      - r_ploigos_sub.resources is defined
      - r_ploigos_sub.resources[0] is defined
      - r_ploigos_sub.resources[0].status is defined
      - r_ploigos_sub.resources[0].status.currentCSV is defined
    retries: 20
    delay: 5

  - name: Register CSV name
    set_fact:
      ploigos_csv_name: "{{ r_ploigos_sub.resources[0].status.currentCSV }}"

  - name: Message
    debug:
      msg: "Ploigos csv name: {{ ploigos_csv_name }}"

  - name: Wait for Ploigos CSV to be succeeded
    k8s_info:
      api_version: operators.coreos.com/v1alpha1
      kind: ClusterServiceVersion
      name: "{{ ploigos_csv_name }}"
      namespace: "{{ ploigos_namespace }}"
    register: r_ploigos_csv
    until: 
      - r_ploigos_csv is defined
      - r_ploigos_csv.resources is defined
      - r_ploigos_csv.resources[0] is defined
      - r_ploigos_csv.resources[0].status is defined
      - r_ploigos_csv.resources[0].status.phase is defined
      - r_ploigos_csv.resources[0].status.phase == "Succeeded"
    retries: 20
    delay: 10
  when:
    - ploigos_cleanup is defined and not (ploigos_cleanup | bool)
