# Tasks for Installing and uninstalling ploigos platform from a cluster
- name: Install Ploigos Platform
  include_tasks:
    file: ./install.yml
  when: ploigos_install | bool

- name: Wait for Ploigos Platform
  include_tasks:
    file: ./wait.yml
  when: ploigos_wait | bool

- name: Remove Ploigos Platform
  include_tasks:
    file: ./uninstall.yml
  when: ploigos_cleanup | bool 