---
- name: Debug Print Subscription
  debug:
    msg: "Subscription is {{ subscription }}"

- name: Uninstall Operator
  block:
    - name: Print CSV
      debug:
        msg: "current csv is: {{ subscription.status.currentCSV | default ('[NONE]')}}"
    - name: Set CSV
      set_fact:
        current_csv: "{{ subscription.status.currentCSV | default('0.0.0') }}"
        current_namespace: "{{ subscription.metadata.namespace | default('default') }}"

    - name: Delete Subscription
      k8s:
        state: absent
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: "{{ subscription.metadata.name }}"
        namespace: "{{ current_namespace }}"

    - name: Delete ClusterServiceVersion
      k8s:
        state: absent
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ current_csv }}"
        namespace: "{{ current_namespace }}"
        wait: true
